-- SQL Schema
CREATE TABLE IF NOT EXISTS Firmalar (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirmaKodu VARCHAR(20) UNIQUE NOT NULL,
    Unvan VARCHAR(100) NOT NULL,
    VergiDairesi VARCHAR(50),
    VergiNo VARCHAR(20),
    AktifMi BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Kullanicilar (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    KullaniciAdi VARCHAR(50) UNIQUE NOT NULL,
    SifreHash VARCHAR(255) NOT NULL,
    AdSoyad VARCHAR(100),
    Rol VARCHAR(20) CHECK (Rol IN ('Admin', 'User', 'Depo', 'Muhasebe')) NOT NULL,
    AktifMi BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Cari_Hesaplar (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CariKodu VARCHAR(30) UNIQUE NOT NULL,
    Unvan VARCHAR(150) NOT NULL,
    VergiDairesi VARCHAR(50),
    VergiNo VARCHAR(20),
    Sehir VARCHAR(50),
    Ilce VARCHAR(50),
    Adres TEXT,
    Telefon VARCHAR(20),
    GsmKisi VARCHAR(100),
    Eposta VARCHAR(100),
    Notlar TEXT,
    Bakiye DECIMAL(15, 2) DEFAULT 0.00,
    RiskLimiti DECIMAL(15, 2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS Urunler (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UrunKodu VARCHAR(30) UNIQUE NOT NULL,
    UrunAdi VARCHAR(150) NOT NULL,
    Miktar DECIMAL(15, 4) DEFAULT 0.0000,
    RezerveMiktar DECIMAL(15, 4) DEFAULT 0.0000,
    Birim VARCHAR(10) DEFAULT 'Adet',
    SatisFiyati DECIMAL(15, 2) DEFAULT 0.00,
    Maliyet DECIMAL(15, 2) DEFAULT 0.00,
    KritikStokSeviyesi DECIMAL(15, 4) DEFAULT 10.0000,
    IsPaketUrun BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Stok_Log (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UrunID INTEGER NOT NULL,
    IslemTuru VARCHAR(50) NOT NULL,
    EskiMiktar DECIMAL(15, 4),
    YeniMiktar DECIMAL(15, 4),
    Aciklama TEXT,
    Tarih DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(UrunID) REFERENCES Urunler(ID)
);

CREATE TABLE IF NOT EXISTS Urun_Receteleri (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AnaUrunID INTEGER NOT NULL,
    AltUrunID INTEGER NOT NULL,
    Miktar DECIMAL(15, 4) NOT NULL,
    FOREIGN KEY(AnaUrunID) REFERENCES Urunler(ID),
    FOREIGN KEY(AltUrunID) REFERENCES Urunler(ID)
);

CREATE TABLE IF NOT EXISTS Siparisler (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SiparisNo VARCHAR(30) UNIQUE NOT NULL,
    CariID INTEGER NOT NULL,
    Tarih DATETIME DEFAULT CURRENT_TIMESTAMP,
    DovizKuru DECIMAL(10, 4) DEFAULT 1.0000,
    Aciklama TEXT,
    Durum VARCHAR(20) CHECK (Durum IN ('Açık', 'Hazır', 'Kısmi Sevk', 'Tamamlandı', 'İptal')) DEFAULT 'Açık',
    FOREIGN KEY(CariID) REFERENCES Cari_Hesaplar(ID)
);

CREATE TABLE IF NOT EXISTS Siparis_Detay (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SiparisID INTEGER NOT NULL,
    UrunID INTEGER NOT NULL,
    SipMiktar DECIMAL(15, 4) NOT NULL,
    SevkEdilen DECIMAL(15, 4) DEFAULT 0.0000,
    Kalan DECIMAL(15, 4) NOT NULL,
    BirimFiyat DECIMAL(15, 2) NOT NULL,
    Maliyet DECIMAL(15, 2) NOT NULL,
    FOREIGN KEY(SiparisID) REFERENCES Siparisler(ID),
    FOREIGN KEY(UrunID) REFERENCES Urunler(ID)
);

CREATE TABLE IF NOT EXISTS Sevkiyatlar (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SevkiyatNo VARCHAR(30) NOT NULL,
    EvrakTuru VARCHAR(20) CHECK (EvrakTuru IN ('İrsaliye', 'Fatura')) NOT NULL,
    SiparisID INTEGER NOT NULL,
    CariID INTEGER NOT NULL,
    Tarih DATETIME DEFAULT CURRENT_TIMESTAMP,
    ToplamTutar DECIMAL(15, 2) DEFAULT 0.00,
    FOREIGN KEY(SiparisID) REFERENCES Siparisler(ID),
    FOREIGN KEY(CariID) REFERENCES Cari_Hesaplar(ID)
);

CREATE TABLE IF NOT EXISTS Sevkiyat_Detay (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SevkiyatID INTEGER NOT NULL,
    UrunID INTEGER NOT NULL,
    Miktar DECIMAL(15, 4) NOT NULL,
    BirimFiyat DECIMAL(15, 2) NOT NULL,
    FOREIGN KEY(SevkiyatID) REFERENCES Sevkiyatlar(ID),
    FOREIGN KEY(UrunID) REFERENCES Urunler(ID)
);

CREATE TABLE IF NOT EXISTS Faturalar (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FaturaNo VARCHAR(30) UNIQUE NOT NULL,
    FaturaTipi VARCHAR(20) CHECK (FaturaTipi IN ('Satış', 'Alış', 'İade')) NOT NULL,
    SiparisID INTEGER,
    CariID INTEGER NOT NULL,
    Tarih DATETIME DEFAULT CURRENT_TIMESTAMP,
    ToplamTutar DECIMAL(15, 2) NOT NULL,
    KDVTutari DECIMAL(15, 2) NOT NULL,
    GenelToplam DECIMAL(15, 2) NOT NULL,
    DovizKuru DECIMAL(10, 4) DEFAULT 1.0000,
    Aciklama TEXT,
    IsEFatura BOOLEAN DEFAULT 0,
    EntegrasyonDurumu VARCHAR(30) DEFAULT 'Taslak',
    FOREIGN KEY(SiparisID) REFERENCES Siparisler(ID),
    FOREIGN KEY(CariID) REFERENCES Cari_Hesaplar(ID)
);

CREATE TABLE IF NOT EXISTS Fatura_Detay (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FaturaID INTEGER NOT NULL,
    UrunID INTEGER NOT NULL,
    Miktar DECIMAL(15, 4) NOT NULL,
    BirimFiyat DECIMAL(15, 2) NOT NULL,
    ToplamTutar DECIMAL(15, 2) NOT NULL,
    FOREIGN KEY(FaturaID) REFERENCES Faturalar(ID),
    FOREIGN KEY(UrunID) REFERENCES Urunler(ID)
);